CREATE TABLE IF NOT EXISTS STAKEHOLDER (
    NAME VARCHAR,
    EMAIL VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS PRIM_GROUP (
    NAME VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS KPI (
    NAME VARCHAR,
    DESCRIPTION VARCHAR,
    GRANULARITY INT
);

CREATE TABLE IF NOT EXISTS GROUP_MEMBER (
    STAKEHOLDER_ID INT,
    PRIM_GROUP_ID INT,
    IS_LEADER BOOLEAN,
    IS_AUTHORITY BOOLEAN
);

CREATE TABLE IF NOT EXISTS GROUP_KPI (
    PRIM_GROUP_ID INT,
    KPI_ID INT
);

CREATE TABLE IF NOT EXISTS PRIM_TASK (
    NAME VARCHAR,
    DESCRIPTION VARCHAR,
    STATUS INT,
    DUE_DATE VARCHAR,
    REQUESTER_ID INT,
    SR_INCLUDE BOOLEAN,
    LAST_SR_DATE DATE,
    LAST_UPDATED DATE
);

CREATE TABLE IF NOT EXISTS SUB_TASK (
    PRIM_TASK_ID INT,
    DESCRIPTION VARCHAR,
    STATUS INT,
    START_DATE DATE,
    END_DATE DATE,
    SR_INCLUDE BOOLEAN
);

CREATE TABLE IF NOT EXISTS TASK_KPI (
    PRIM_TASK_ID INT,
    SUB_TASK_ID INT,
    KPI_ID INT
);

CREATE TABLE IF NOT EXISTS TRANSACTION_LOG (
    ACTION INT,
    PRIM_TASK_ID INT,
    SUB_TASK_ID INT,
    CREATED_ON DATE,
    COMMENTS VARCHAR
);